version: '3.7'

services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    volumes:
      - ./mysql:/var/lib/mysql

  wordpress:
    image: wordpress:5.5.1-php7.2
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_CONFIG_EXTRA: |
        /* Enable debug mode*/
        define('WP_DEBUG', true);
        define( 'WP_DEBUG_LOG', '/dev/stdout' );
    volumes:
      - ./usr:/var/www/html/wp-content/themes/usr
